(require 'luis-elisp)
(require 'luis-erlang)
(require 'luis-haskell)
(require 'luis-markdown)
(require 'luis-rst)
(require 'luis-latex)
(require 'luis-shell)
(require 'luis-css)
(require 'luis-swift)
(require 'luis-apache)
(require 'luis-python)
(require 'luis-nxc)
(require 'luis-objc)
(require 'luis-c)
(require 'luis-org)
(require 'luis-java)

(provide 'luis-modes)
