;; -*- lexical-binding: t; -*-

(require 'luis-elisp)
(require 'luis-markdown)
(require 'luis-latex)
(require 'luis-shell)
(require 'luis-css)
(require 'luis-swift)
(require 'luis-apache)
(require 'luis-python)
(require 'luis-c)
(require 'luis-org)
(require 'luis-asm)
(require 'luis-lua)
(require 'luis-java)
(require 'luis-scala)
(require 'luis-make)
(require 'luis-xml)
(require 'luis-rust)

(provide 'luis-modes)
