(add-to-list 'load-path "~/.emacs.d/lisp/languages")
(load "luis-elisp.el")
(load "luis-erlang.el")
(load "luis-haskell.el")
(load "luis-markdown.el")
(load "luis-rst.el")
(load "luis-latex.el")
(load "luis-shell.el")
(load "luis-css.el")
(load "luis-swift.el")
(load "luis-apache.el")
(load "luis-python.el")
(load "luis-nxc.el")
(load "luis-objc.el")

(provide 'luis-languages)
