(add-to-list 'load-path "~/.emacs.d/customizations/languages")
(load "my-elisp.el")
(load "my-erlang.el")
(load "my-haskell.el")
(load "my-javascript.el")
(load "my-markdown.el")
(load "my-rst.el")
(load "my-latex.el")
(load "my-shell.el")
(load "my-css.el")
(load "my-swift.el")
(load "my-apache.el")
(load "my-python.el")
